---
deployment:
  tasks:
    - BRANCH=$(git rev-parse --abbrev-ref HEAD) && if [ "$BRANCH" = "ppe" ]; then DEPLOYPATH=$HOME/public_html/ppe.nitrateonline.com/; else DEPLOYPATH=$HOME/public_html/nitrateonline.com/; fi && /bin/cp -R .htaccess * $DEPLOYPATH
