---
deployment:
  tasks:
    - BRANCH=$(git rev-parse --abbrev-ref HEAD)
    - if [ "$BRANCH" = "ppe" ]; then export DEPLOYPATH=$HOME/public_html/ppe.nitrateonline.com/; else export DEPLOYPATH=$HOME/public_html/nitrateonline.com/; fi
